# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cschen/pcl_exercise

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cschen/pcl_exercise

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cschen/pcl_exercise/CMakeFiles /home/cschen/pcl_exercise/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cschen/pcl_exercise/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example_fast_point_feature_histograms

# Build rule for target.
example_fast_point_feature_histograms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_fast_point_feature_histograms
.PHONY : example_fast_point_feature_histograms

# fast build rule for target.
example_fast_point_feature_histograms/fast:
	$(MAKE) -f src/CMakeFiles/example_fast_point_feature_histograms.dir/build.make src/CMakeFiles/example_fast_point_feature_histograms.dir/build
.PHONY : example_fast_point_feature_histograms/fast

#=============================================================================
# Target rules for targets named example_normal_estimation

# Build rule for target.
example_normal_estimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_normal_estimation
.PHONY : example_normal_estimation

# fast build rule for target.
example_normal_estimation/fast:
	$(MAKE) -f src/CMakeFiles/example_normal_estimation.dir/build.make src/CMakeFiles/example_normal_estimation.dir/build
.PHONY : example_normal_estimation/fast

#=============================================================================
# Target rules for targets named example_point_feature_histograms

# Build rule for target.
example_point_feature_histograms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_point_feature_histograms
.PHONY : example_point_feature_histograms

# fast build rule for target.
example_point_feature_histograms/fast:
	$(MAKE) -f src/CMakeFiles/example_point_feature_histograms.dir/build.make src/CMakeFiles/example_point_feature_histograms.dir/build
.PHONY : example_point_feature_histograms/fast

#=============================================================================
# Target rules for targets named normal_estimation_using_integral_images

# Build rule for target.
normal_estimation_using_integral_images: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 normal_estimation_using_integral_images
.PHONY : normal_estimation_using_integral_images

# fast build rule for target.
normal_estimation_using_integral_images/fast:
	$(MAKE) -f src/CMakeFiles/normal_estimation_using_integral_images.dir/build.make src/CMakeFiles/normal_estimation_using_integral_images.dir/build
.PHONY : normal_estimation_using_integral_images/fast

#=============================================================================
# Target rules for targets named pc_test

# Build rule for target.
pc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pc_test
.PHONY : pc_test

# fast build rule for target.
pc_test/fast:
	$(MAKE) -f src/CMakeFiles/pc_test.dir/build.make src/CMakeFiles/pc_test.dir/build
.PHONY : pc_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example_fast_point_feature_histograms"
	@echo "... example_normal_estimation"
	@echo "... example_point_feature_histograms"
	@echo "... normal_estimation_using_integral_images"
	@echo "... pc_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

